### ISSUE TITLE
issue about x2 SR training process

### ISSUE THREAD

**Issue by wwlCape** [megvii-research/DCLS-SR#2]
![image](https://user-images.githubusercontent.com/38447393/162661587-fae5cd5b-4178-4e85-85d9-dd00fa45dd97.png)
Hi, when I train the model under setting1_x2, I can not obtain a good result. Maybe I missed something in my training. Could you give some advice on it?

```
#### general settings
name: DCLSx2_setting1
use_tb_logger: true
model: blind
distortion: sr
scale: 2
gpu_ids: [0, 1, 2, 3]
pca_matrix_path: ../../../pca_matrix/DCLS/pca_matrix.pth

degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 2.0
  rate_iso: 1.0
  random_disturb: false

#### datasets
datasets:
  train:
    name: DIV2K
    mode: GT
    dataroot_GT: /datasets/DF2K/HR/x2HR.lmdb

    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 64
    GT_size: 128
    LR_size: 64
    use_flip: true
    use_rot: true
    color: RGB
  val:
    name: Set5
    mode: LQGT
    dataroot_GT: /datasets/Set5/x2HR.lmdb
    dataroot_LQ: /datasets/Set5/x2LRblur.lmdb

#### network structures
network_G:
  which_model_G: DCLS
  setting:
    nf: 64
    nb: 10
    ng: 5
    input_para: 256
    kernel_size: 21

#### path
path:
  pretrain_model_G: ~
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_E: !!float 4e-4
  lr_scheme: MultiStepLR
  beta1: 0.9
  beta2: 0.99
  niter: 500000
  warmup_iter: -1  # no warm up
  lr_steps: [200000, 400000]
  lr_gamma: 0.5
  eta_min: !!float 1e-7

  pixel_criterion: l1
  pixel_weight: 1.0

  manual_seed: 0
  val_freq: !!float 100

#### logger
logger:
  print_freq: 20
  save_checkpoint_freq: !!float 1000

```
This is the config settings. Thank you for your reply!
