### ISSUE TITLE
About noise

### ISSUE THREAD

**Issue by xiab3369** [megvii-research/DCLS-SR#3]
Thanks for your interesting work! As I reproduce your work, I find that you don't add any noise for anisotropic kernel training as your paper claimed. So is there any bug?

**Comment by Algolzw** [comment]
As the same as previous works such as KernelGAN, IKC, and DAN, we didn't add noises in the anisotropic setting. However, if you want to evaluate our method on noisy images, you should modify the setting (in the options file) as follows and re-train the model:

```
degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 4.0
  rate_iso: 1.0
  random_disturb: false
  ######### add noises ###########
  noise: True
  # noise_high: 0.0588 # noise level 15: 15 / 255.
  noise_high: 0.1176 # noise level 30: 30 / 255.
  ################################
```
