### ISSUE TITLE
关于怎么给图片添加噪声的问题

### ISSUE THREAD

**Issue by lanhoulllllllllll** [megvii-research/DCLS-SR#47]
![image](https://github.com/megvii-research/DCLS-SR/assets/121162076/19cbbdce-4ac3-405f-a9fb-c13f3ce10837)
作者您好，如果要给图片添加噪声，是只要把self.noise改为ture就行了嘛，关于Noise_level该怎么设置呢，

**Comment by Algolzw** [comment]
你好，添加噪声的话只需要这样修改option file:

```
degradation:
  random_kernel: True
  ksize: 21
  code_length: 10
  sig_min: 0.2
  sig_max: 4.0
  rate_iso: 1.0
  random_disturb: false
  noise: True
  # noise_high: 0.0588 # level 15: 15 / 255.
  noise_high: 0.1176 # level 30: 30 / 255.
```
